---
AWSTemplateFormatVersion: "2010-09-09"

Description: Template to deploy an S3 Bucket for cross-account shared use

Parameters:
  Name:
    Type: String
    Description: Name to identify resources of this stack
  Stage:
    Type: String
    Description: The stage of this stack deployment
  Versioned:
    Type: String
    Description: Whether to enable versioning on this bucket
    AllowedValues:
      - true
      - false
  PermittedRoles:
    Type: List<String>
    Description: A comma separated list of AWS Role ARNs that should have read access
    Default: ""

Conditions:
  IsVersioned: !Equals [!Ref Versioned, true]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketName: !Join ["-", [!Sub "${AWS::StackName}", !Ref Name, !Ref Stage]]
      VersioningConfiguration: !If
        - IsVersioned
        - Status: Enabled
        - !Ref AWS::NoValue

  BucketReadRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref PermittedRoles
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Join ["/", [!GetAtt Bucket.Arn, "*"]]
                  - !GetAtt Bucket.Arn
